/**
 * tools/runtime.ts
 * Tools de Agent Runtime — consumidas pelos agentes durante atendimento.
 * Spec: PlugHub v24.0 seções 4.5, 4.2, 3.4a
 *
 * Grupo: Agent Runtime (7 tools)
 *   agent_login, agent_ready, agent_busy, agent_done,
 *   agent_pause, agent_logout, insight_register
 *
 * Invariantes:
 * - Nenhuma lógica de negócio — apenas exposição de tools
 * - Toda tool valida input com @plughub/schemas antes de qualquer operação
 * - Erros retornados como MCP error response (isError: true) — nunca throw não tratado
 * - Nenhuma tool persiste estado em memória — Redis ou Kafka apenas
 * - Todas as chaves Redis são prefixadas com {tenant_id}:
 */

import { z }            from "zod"
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import {
  AgentDoneV2Schema,
  SessionOutcomeSchema,
} from "@plughub/schemas"
import type { RedisClient }    from "../infra/redis"
import { keys }                from "../infra/redis"
import type { KafkaProducer }  from "../infra/kafka"
import type { RegistryClient } from "../infra/registry-client"
import {
  signSessionToken,
  verifySessionToken,
  InvalidTokenError,
  SESSION_TOKEN_TTL_S,
} from "../infra/jwt"
import { emitSessionOpened } from "../lib/usage-emitter"

// ─── Dependências injetadas ───────────────────────────────────────────────────

export interface RuntimeDeps {
  redis:    RedisClient
  kafka:    KafkaProducer
  registry: RegistryClient
}

// ─── Schemas de input das tools ───────────────────────────────────────────────

const AgentLoginInputSchema = z.object({
  agent_type_id: z.string().min(1),
  instance_id:   z.string().min(1),
  /** tenant_id: inferido do JWT nas demais tools; aqui é o ponto de entrada */
  tenant_id:     z.string().min(1),
})

const AgentReadyInputSchema = z.object({
  session_token: z.string().min(1),
})

const AgentBusyInputSchema = z.object({
  session_token:  z.string().min(1),
  /** session_id da sessão alocada pelo Routing Engine */
  session_id:     z.string().min(1),
  /** participant_id UUID gerado pelo Routing Engine para este agente nesta sessão */
  participant_id: z.string().uuid(),
})

const AgentDoneInputSchema = z.object({
  session_token:   z.string().min(1),
  /**
   * session_id da sessão que está sendo encerrada.
   * Aceita tanto o novo formato (sess_YYYYMMDDTHHMMSS_ULID) quanto UUIDs legados.
   */
  session_id:      z.string().min(1),
  /** participant_id UUID do agente na sessão (retornado pelo Routing Engine na alocação) */
  participant_id:  z.string().uuid(),
  outcome:         SessionOutcomeSchema,
  /**
   * Descrição resumida do desfecho — obrigatório e nunca vazio.
   * Ex: "Problema de portabilidade resolvido", "Transferido para retenção humana"
   */
  issue_status:    z.string().min(1),
  /** Obrigatório quando outcome !== "resolved" */
  handoff_reason:  z.string().optional(),
  /** Se omitido, o servidor usa o timestamp atual */
  completed_at:    z.string().datetime().optional(),
  /**
   * ID de conferência — opcional. Quando presente, indica que este agent_done
   * encerra apenas a PARTICIPAÇÃO do especialista, não a sessão do cliente.
   * Spec seção 5 — conference mode agent_done.
   */
  conference_id:   z.string().uuid().optional(),
}).refine(
  (d) => d.outcome === "resolved" || d.handoff_reason !== undefined,
  { message: "handoff_reason é obrigatório quando outcome !== 'resolved'", path: ["handoff_reason"] }
)

const AgentPauseInputSchema = z.object({
  session_token: z.string().min(1),
})

const AgentLogoutInputSchema = z.object({
  session_token: z.string().min(1),
})

const AgentHeartbeatInputSchema = z.object({
  session_token: z.string().min(1),
})

const InsightRegisterInputSchema = z.object({
  session_token: z.string().min(1),
  session_id:    z.string().min(1),
  /**
   * Hierarchical category — must have prefix insight.conversa.*
   * insight.historico.* is generated by external systems, not by the agent.
   * Spec 3.4a.
   */
  category: z.string().regex(
    /^insight\.conversa\./,
    "insight_register only accepts insight.conversa.* categories — " +
    "use external systems for insight.historico.*"
  ),
  content:    z.record(z.unknown()),
  priority:   z.number().int().min(0).max(100),
  /** Expiry datetime — defaults to session TTL (4h) if omitted */
  expires_at: z.string().datetime().optional(),
})

// ─── Helpers de resposta ──────────────────────────────────────────────────────

type ToolResult = {
  isError?: true
  content: Array<{ type: "text"; text: string }>
}

function ok(data: unknown): ToolResult {
  return { content: [{ type: "text" as const, text: JSON.stringify(data) }] }
}

function mcpError(code: string, message: string): ToolResult {
  return {
    isError: true,
    content: [{ type: "text" as const, text: JSON.stringify({ error: code, message }) }],
  }
}

function handleCaughtError(e: unknown): ToolResult {
  if (e instanceof z.ZodError) {
    return mcpError(
      "validation_error",
      e.errors.map(x => `${x.path.join(".")}: ${x.message}`).join("; ")
    )
  }
  if (e instanceof InvalidTokenError) {
    return mcpError("invalid_token", e.message)
  }
  return mcpError("internal_error", e instanceof Error ? e.message : String(e))
}

// ─── Registro das tools ───────────────────────────────────────────────────────

export function registerRuntimeTools(server: McpServer, deps: RuntimeDeps): void {
  const { redis, kafka, registry } = deps

  // ── agent_login ───────────────────────────────────────────────────────────
  server.tool(
    "agent_login",
    "Registra instância de agente. Valida agent_type_id no Agent Registry. " +
    "Emite session_token JWT. Instância não recebe conversas até agent_ready. Spec 4.5.",
    AgentLoginInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const { agent_type_id, instance_id, tenant_id } = AgentLoginInputSchema.parse(input)

        // Valida agent_type_id no Agent Registry
        const agentType = await registry.getAgentType(tenant_id, agent_type_id)
        if (!agentType) {
          return mcpError(
            "agent_type_not_found",
            `agent_type_id '${agent_type_id}' não encontrado no tenant '${tenant_id}'`
          )
        }

        // Emite session_token JWT (inclui permissions para validação local em invoke)
        const session_token    = signSessionToken({
          tenant_id,
          agent_type_id,
          instance_id,
          permissions: agentType.permissions,
        })
        const token_expires_at = new Date(Date.now() + SESSION_TOKEN_TTL_S * 1000).toISOString()

        // Persiste estado da instância no Redis
        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        await redis.hset(instanceKey, {
          state:                   "logged_in",
          agent_type_id,
          current_sessions:        "0",
          max_concurrent_sessions: String(agentType.max_concurrent_sessions),
          execution_model:         agentType.execution_model ?? "stateless",
          pools:                   JSON.stringify(agentType.pools),
          logged_in_at:            new Date().toISOString(),
        })
        await redis.expire(instanceKey, SESSION_TOKEN_TTL_S)

        // Índice token → instance_id
        await redis.set(
          keys.agentToken(tenant_id, session_token),
          instance_id,
          "EX",
          SESSION_TOKEN_TTL_S
        )

        // Evento de ciclo de vida para o Routing Engine
        await kafka.publish("agent.lifecycle", {
          event:         "agent_login",
          tenant_id,
          agent_type_id,
          instance_id,
          timestamp:     new Date().toISOString(),
        })

        return ok({ session_token, token_expires_at, instance_id })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── agent_ready ───────────────────────────────────────────────────────────
  server.tool(
    "agent_ready",
    "Coloca a instância na fila de alocação dos pools declarados. Spec 4.5.",
    AgentReadyInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const { session_token } = AgentReadyInputSchema.parse(input)
        const { tenant_id, instance_id } = verifySessionToken(session_token)

        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        const state = await redis.hget(instanceKey, "state")
        if (!state) {
          return mcpError("instance_not_found", `Instância '${instance_id}' não encontrada`)
        }
        if (state !== "logged_in" && state !== "paused") {
          return mcpError(
            "invalid_state",
            `Instância está em estado '${state}' — esperado 'logged_in' ou 'paused'`
          )
        }

        // Transição válida: logged_in → ready  (primeiro ready após login)
        //                   paused   → ready  (retomada após pausa)
        await redis.hset(instanceKey, "state", "ready")

        // Adiciona aos pools declarados
        const poolsRaw = await redis.hget(instanceKey, "pools")
        const pools: string[] = poolsRaw ? (JSON.parse(poolsRaw) as string[]) : []
        for (const poolId of pools) {
          await redis.sadd(keys.poolAvailable(tenant_id, poolId), instance_id)
        }

        // Ler campos necessários para o Routing Engine poder criar a instância corretamente
        const agentTypeId      = await redis.hget(instanceKey, "agent_type_id")      ?? ""
        const executionModel   = await redis.hget(instanceKey, "execution_model")    ?? "stateless"
        const maxConcurrentRaw = await redis.hget(instanceKey, "max_concurrent_sessions") ?? "1"
        const currentSessRaw   = await redis.hget(instanceKey, "current_sessions")   ?? "0"

        await kafka.publish("agent.lifecycle", {
          event:                   "agent_ready",
          tenant_id,
          instance_id,
          agent_type_id:           agentTypeId,
          pools,
          status:                  "ready",
          execution_model:         executionModel,
          max_concurrent_sessions: parseInt(maxConcurrentRaw, 10),
          current_sessions:        parseInt(currentSessRaw, 10),
          timestamp:               new Date().toISOString(),
        })

        return ok({ status: "ready", timestamp: new Date().toISOString() })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── agent_busy ────────────────────────────────────────────────────────────
  server.tool(
    "agent_busy",
    "Atualiza current_sessions ao iniciar o atendimento de uma sessão. " +
    "Remove da fila se atingir max_concurrent_sessions. Spec seção 5.",
    AgentBusyInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const { session_token, session_id, participant_id } = AgentBusyInputSchema.parse(input)
        const { tenant_id, instance_id } = verifySessionToken(session_token)

        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        const state = await redis.hget(instanceKey, "state")
        if (!state) {
          return mcpError("instance_not_found", `Instância '${instance_id}' não encontrada`)
        }
        if (state !== "ready" && state !== "busy") {
          return mcpError(
            "invalid_state",
            `Instância está em estado '${state}' — esperado 'ready' ou 'busy'`
          )
        }

        // Incremento atômico via HINCRBY
        const currentSessions = await redis.hincrby(instanceKey, "current_sessions", 1)
        const maxRaw = await redis.hget(instanceKey, "max_concurrent_sessions")
        const max    = maxRaw ? parseInt(maxRaw, 10) : 1

        await redis.hset(instanceKey, "state", "busy")

        // Rastreia sessão ativa na instância (usando session_id como identificador)
        await redis.sadd(keys.agentConversations(tenant_id, instance_id), session_id)

        // Armazena mapeamento participant_id → instance_id para lookup em agent_done
        await redis.set(
          `${tenant_id}:participant:${participant_id}:instance`,
          instance_id,
          "EX",
          14400  // 4h — mesma janela da sessão
        )

        // Se atingiu o limite, remove dos pools para não receber novas sessões
        if (currentSessions >= max) {
          const poolsRaw = await redis.hget(instanceKey, "pools")
          const pools: string[] = poolsRaw ? (JSON.parse(poolsRaw) as string[]) : []
          for (const poolId of pools) {
            await redis.srem(keys.poolAvailable(tenant_id, poolId), instance_id)
          }
        }

        await kafka.publish("agent.lifecycle", {
          event:            "agent_busy",
          tenant_id,
          instance_id,
          participant_id,
          session_id,
          current_sessions: currentSessions,
          timestamp:        new Date().toISOString(),
        })

        // Notifica o cliente que o agente entrou na conversa (visibility: all)
        try {
          await (redis as any).xadd(
            `session:${session_id}:stream`,
            "*",
            "event_id",   crypto.randomUUID(),
            "type",       "participant_joined",
            "timestamp",  new Date().toISOString(),
            "author",     JSON.stringify({ participant_id, instance_id, role: "primary" }),
            "visibility", JSON.stringify("all"),
            "payload",    JSON.stringify({ participant_id, instance_id }),
          )
        } catch { /* stream não disponível — non-fatal */ }

        // Metering: emite sessions na primeira vez que esta sessão é servida.
        // Lê o canal da sessão do Redis; fallback "webchat" se meta não disponível.
        let sessionChannel = "webchat"
        try {
          const metaRaw = await redis.get(`session:${session_id}:meta`)
          if (metaRaw) {
            const meta = JSON.parse(metaRaw) as Record<string, unknown>
            if (typeof meta["channel"] === "string") sessionChannel = meta["channel"]
          }
        } catch { /* non-fatal — usa fallback */ }
        void emitSessionOpened(kafka, redis, { tenant_id, session_id, channel: sessionChannel })

        return ok({ status: "busy", session_id, participant_id, current_sessions: currentSessions, timestamp: new Date().toISOString() })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── agent_done ────────────────────────────────────────────────────────────
  server.tool(
    "agent_done",
    "Sinaliza conclusão do atendimento. Valida AgentDonePayload via @plughub/schemas " +
    "(incluindo .refine()). Decrementa current_sessions. Publica em conversations.events. Spec 4.2.",
    AgentDoneInputSchema._def.schema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const parsed = AgentDoneInputSchema.parse(input)
        const {
          session_token, session_id, participant_id, outcome,
          issue_status, handoff_reason,
          conference_id,   // presente em modo conferência — omite session.closed
        } = parsed
        const completed_at = parsed.completed_at ?? new Date().toISOString()

        const { tenant_id, instance_id, agent_type_id } = verifySessionToken(session_token)

        // Validação completa via @plughub/schemas AgentDoneV2 — inclui .refine() para handoff_reason
        const payload = AgentDoneV2Schema.parse({
          session_id,
          participant_id,
          agent_type_id: agent_type_id ?? instance_id,
          outcome,
          issue_status,
          handoff_reason,
          completed_at,
        })

        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        const instanceState = await redis.hget(instanceKey, "state")
        if (!instanceState) {
          return mcpError("instance_not_found", `Instância '${instance_id}' não encontrada`)
        }

        // Decrementa current_sessions (atômico via HINCRBY)
        const afterDecrement  = await redis.hincrby(instanceKey, "current_sessions", -1)
        const currentSessions = Math.max(0, afterDecrement)
        if (afterDecrement < 0) {
          await redis.hset(instanceKey, "current_sessions", "0")
        }

        // Remove sessão do SET de sessões ativas
        await redis.srem(keys.agentConversations(tenant_id, instance_id), session_id)

        // Remove mapeamento participant_id → instance_id
        await redis.del(`${tenant_id}:participant:${participant_id}:instance`)

        // Transição de estado pós-conclusão
        if (instanceState === "draining" && currentSessions === 0) {
          await redis.del(instanceKey)
          await redis.del(keys.agentToken(tenant_id, session_token))
        } else if (currentSessions === 0 && instanceState !== "paused") {
          await redis.hset(instanceKey, "state", "ready")
        }

        // Notifica o cliente que o agente saiu da conversa (visibility: all)
        try {
          await (redis as any).xadd(
            `session:${session_id}:stream`,
            "*",
            "event_id",   crypto.randomUUID(),
            "type",       "participant_left",
            "timestamp",  new Date().toISOString(),
            "author",     JSON.stringify({ participant_id, instance_id, role: "primary" }),
            "visibility", JSON.stringify("all"),
            "payload",    JSON.stringify({ participant_id, instance_id, reason: outcome }),
          )
        } catch { /* stream não disponível — non-fatal */ }

        // Publica em agent.done (Kafka) — consumido por Rules Engine e Analytics
        await kafka.publish("agent.done", {
          session_id:     payload.session_id,
          tenant_id,
          instance_id,
          participant_id: payload.participant_id,
          agent_type_id:  payload.agent_type_id,
          outcome:        payload.outcome,
          issue_status:   payload.issue_status,
          handoff_reason: payload.handoff_reason ?? undefined,
          completed_at:   payload.completed_at,
          timestamp:      new Date().toISOString(),
        })

        // Notifica o cliente via conversations.outbound — envia session.closed
        // EXCEÇÃO (modo conferência): quando conference_id está presente, encerra
        // apenas a participação do especialista — NÃO a sessão do cliente.
        if (!conference_id) {
          try {
            let contactId = session_id   // fallback
            let channel   = "webchat"
            const metaRaw = await redis.get(`session:${session_id}:meta`)
            if (metaRaw) {
              const meta = JSON.parse(metaRaw) as Record<string, string>
              if (meta["contact_id"]) contactId = meta["contact_id"]
              if (meta["channel"])    channel   = meta["channel"]
            }
            await kafka.publish("conversations.outbound", {
              type:       "session.closed",
              contact_id: contactId,
              session_id,
              channel,
              reason:     payload.outcome,
            })
          } catch { /* Non-fatal — WebSocket do cliente expira pelo TTL da sessão */ }
        }

        // Modo conferência: sinaliza conclusão do especialista sem encerrar a sessão
        if (conference_id) {
          try {
            await kafka.publish("conversations.events", {
              event_type:    "conference_agent_completed",
              session_id,
              conference_id,
              participant_id,
              instance_id,
              outcome:       payload.outcome,
              timestamp:     new Date().toISOString(),
            })
          } catch { /* Non-fatal */ }
        }

        // Evento de ciclo de vida para o Routing Engine
        await kafka.publish("agent.lifecycle", {
          event:            "agent_done",
          tenant_id,
          instance_id,
          participant_id,
          session_id,
          current_sessions: currentSessions,
          timestamp:        new Date().toISOString(),
        })

        return ok({
          session_id,
          participant_id,
          outcome:      payload.outcome,
          acknowledged: true,
          completed_at: payload.completed_at,
        })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── agent_pause ───────────────────────────────────────────────────────────
  server.tool(
    "agent_pause",
    "Remove instância da fila de alocação. Sessões ativas não são interrompidas. Spec 4.5.",
    AgentPauseInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const { session_token } = AgentPauseInputSchema.parse(input)
        const { tenant_id, instance_id } = verifySessionToken(session_token)

        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        const state = await redis.hget(instanceKey, "state")
        if (!state) {
          return mcpError("instance_not_found", `Instância '${instance_id}' não encontrada`)
        }
        if (state !== "ready" && state !== "busy") {
          return mcpError(
            "invalid_state",
            `Instância está em estado '${state}' — não pode pausar`
          )
        }

        await redis.hset(instanceKey, "state", "paused")

        // Remove dos pools — não receberá novas conversas
        const poolsRaw = await redis.hget(instanceKey, "pools")
        const pools: string[] = poolsRaw ? (JSON.parse(poolsRaw) as string[]) : []
        for (const poolId of pools) {
          await redis.srem(keys.poolAvailable(tenant_id, poolId), instance_id)
        }

        await kafka.publish("agent.lifecycle", {
          event:     "agent_pause",
          tenant_id,
          instance_id,
          timestamp: new Date().toISOString(),
        })

        return ok({ status: "paused", timestamp: new Date().toISOString() })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── agent_logout ──────────────────────────────────────────────────────────
  server.tool(
    "agent_logout",
    "Drain: para alocar novas conversas. Se houver sessões ativas, marca como 'draining'. " +
    "O estado 'logged_out' é atingido após o último agent_done. Spec 4.5.",
    AgentLogoutInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const { session_token } = AgentLogoutInputSchema.parse(input)
        const { tenant_id, instance_id } = verifySessionToken(session_token)

        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        const state = await redis.hget(instanceKey, "state")
        if (!state) {
          return mcpError("instance_not_found", `Instância '${instance_id}' não encontrada`)
        }

        // Remove dos pools — para de receber novas conversas imediatamente
        const poolsRaw = await redis.hget(instanceKey, "pools")
        const pools: string[] = poolsRaw ? (JSON.parse(poolsRaw) as string[]) : []
        for (const poolId of pools) {
          await redis.srem(keys.poolAvailable(tenant_id, poolId), instance_id)
        }

        const currentSessionsRaw = await redis.hget(instanceKey, "current_sessions")
        const activeSessions     = currentSessionsRaw ? parseInt(currentSessionsRaw, 10) : 0

        // Se sem sessões ativas: logged_out imediato. Caso contrário: draining.
        const newState = activeSessions > 0 ? "draining" : "logged_out"

        if (newState === "logged_out") {
          await redis.del(instanceKey)
          await redis.del(keys.agentToken(tenant_id, session_token))
        } else {
          await redis.hset(instanceKey, "state", "draining")
        }

        await kafka.publish("agent.lifecycle", {
          event:           "agent_logout",
          tenant_id,
          instance_id,
          state:           newState,
          active_sessions: activeSessions,
          timestamp:       new Date().toISOString(),
        })

        return ok({
          status:          newState,
          active_sessions: activeSessions,
          timestamp:       new Date().toISOString(),
        })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── agent_heartbeat ───────────────────────────────────────────────────────
  server.tool(
    "agent_heartbeat",
    "Renova o TTL da instância no Redis sinalizando que o agente está vivo. " +
    "Deve ser chamado a cada ~10s em estado ready ou busy. " +
    "A ausência de heartbeat por 30s é detectada pelo Routing Engine como crash. Spec 4.5.",
    AgentHeartbeatInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const { session_token } = AgentHeartbeatInputSchema.parse(input)
        const { tenant_id, instance_id } = verifySessionToken(session_token)

        const instanceKey = keys.agentInstance(tenant_id, instance_id)
        const state = await redis.hget(instanceKey, "state")
        if (!state) {
          return mcpError("instance_not_found", `Instância '${instance_id}' não encontrada`)
        }
        if (state !== "ready" && state !== "busy") {
          return mcpError(
            "invalid_state",
            `Heartbeat inválido no estado '${state}' — esperado 'ready' ou 'busy'`
          )
        }

        await redis.expire(instanceKey, SESSION_TOKEN_TTL_S)

        await kafka.publish("agent.lifecycle", {
          event:       "agent_heartbeat",
          tenant_id,
          instance_id,
          status:      state,
          timestamp:   new Date().toISOString(),
        })

        return ok({ ok: true, timestamp: new Date().toISOString() })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )

  // ── insight_register ──────────────────────────────────────────────────────
  server.tool(
    "insight_register",
    "Registra insight da conversa atual. Aceita apenas insight.conversa.*. " +
    "Persiste no Redis com TTL = duração da sessão. Spec 3.4a.",
    InsightRegisterInputSchema.shape as any,
    async (input: Record<string, unknown>) => {
      try {
        const parsed = InsightRegisterInputSchema.parse(input)
        const { session_token, session_id, category, content, priority, expires_at } = parsed

        // Extra guard: reject insight.historico.* explicitly
        // (regex already blocks it, but this gives a clearer error message)
        if (category.startsWith("insight.historico.")) {
          return mcpError(
            "category_forbidden",
            "insight.historico.* is generated by external systems — " +
            "agents must register only insight.conversa.*"
          )
        }

        const { tenant_id, instance_id } = verifySessionToken(session_token)

        const item_id       = crypto.randomUUID()
        const registered_at = new Date().toISOString()

        // Compute TTL: use expires_at if provided, otherwise default to 4h (typical session duration)
        const DEFAULT_SESSION_TTL_S = 4 * 3600
        let ttlSeconds = DEFAULT_SESSION_TTL_S
        if (expires_at) {
          const remainingMs = new Date(expires_at).getTime() - Date.now()
          ttlSeconds = remainingMs > 0 ? Math.floor(remainingMs / 1000) : DEFAULT_SESSION_TTL_S
        }

        const item = {
          item_id,
          tenant_id,
          source_session_id: session_id,
          source:            instance_id,
          category,
          content,
          priority,
          status:            "pending",
          registered_at,
          ...(expires_at ? { expires_at } : {}),
        }

        await redis.set(
          keys.insight(tenant_id, session_id, item_id),
          JSON.stringify(item),
          "EX",
          ttlSeconds
        )

        return ok({
          item_id,
          session_id,
          category,
          priority,
          registered_at,
          expires_at: expires_at ?? new Date(Date.now() + ttlSeconds * 1000).toISOString(),
        })
      } catch (e) {
        return handleCaughtError(e)
      }
    }
  )
}
